baseURL = "//saihv.github.io"
languageCode = "en-us"
title = "Sai H. Vemprala"
theme = "noteworthy"
staticDir = ["static"]

[params]
	math = true
	email = "mailto:mail@saihv.com"
    twitter = "https://twitter.com/saihv"
	linkedin = "https://linkedin.com/in/saihv"
    googlescholar = "https://scholar.google.com/citations?user=PnaHFhUAAAAJ&hl=en"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "tags"
	name = "publications"
	url = "/pubs/"
	weight = 3

[[menu.main]]
	name = "research"
	identifier = "archives"
	url = "/research/"
	weight = 2

[[menu.main]]
	name = "experience"
	identifier = "exp"
	url = "/exp/"
	weight = 1

[markup]
  [markup.goldmark.renderer]
    unsafe= true